package controllers

import (
	"bytes"
	"crypto/rsa"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

type githubAppConfig struct {
	AppID          string
	InstallationID string
	PrivateKeyPath string
	RepoOwner      string
	RepoName       string
	BotName        string
	BotEmail       string
}

func loadGitHubAppConfig() (githubAppConfig, error) {
	cfg := githubAppConfig{
		AppID:          strings.TrimSpace(os.Getenv("GITHUB_APP_ID")),
		InstallationID: strings.TrimSpace(os.Getenv("GITHUB_APP_INSTALLATION_ID")),
		PrivateKeyPath: strings.TrimSpace(os.Getenv("GITHUB_APP_PRIVATE_KEY_PATH")),
		RepoOwner:      strings.TrimSpace(os.Getenv("GITHUB_REPO_OWNER")),
		RepoName:       strings.TrimSpace(os.Getenv("GITHUB_REPO_NAME")),
		BotName:        strings.TrimSpace(os.Getenv("GITHUB_BOT_NAME")),
		BotEmail:       strings.TrimSpace(os.Getenv("GITHUB_BOT_EMAIL")),
	}
	if cfg.PrivateKeyPath == "" {
		cfg.PrivateKeyPath = strings.TrimSpace(os.Getenv("PRIVATE_KEY_PATH"))
	}
	if cfg.BotName == "" {
		cfg.BotName = "dustbot"
	}
	if cfg.BotEmail == "" {
		cfg.BotEmail = "dustbot@users.noreply.github.com"
	}
	missing := []string{}
	if cfg.AppID == "" {
		missing = append(missing, "GITHUB_APP_ID")
	}
	if cfg.InstallationID == "" {
		missing = append(missing, "GITHUB_APP_INSTALLATION_ID")
	}
	if cfg.PrivateKeyPath == "" {
		missing = append(missing, "GITHUB_APP_PRIVATE_KEY_PATH or PRIVATE_KEY_PATH")
	}
	if cfg.RepoOwner == "" {
		missing = append(missing, "GITHUB_REPO_OWNER")
	}
	if cfg.RepoName == "" {
		missing = append(missing, "GITHUB_REPO_NAME")
	}
	if len(missing) > 0 {
		return cfg, fmt.Errorf("missing github config: %s", strings.Join(missing, ", "))
	}
	return cfg, nil
}

func loadGitHubAppConfigWithRepo(owner, name string) (githubAppConfig, error) {
	cfg, err := loadGitHubAppConfig()
	if err != nil {
		return cfg, err
	}
	if strings.TrimSpace(owner) != "" {
		cfg.RepoOwner = strings.TrimSpace(owner)
	}
	if strings.TrimSpace(name) != "" {
		cfg.RepoName = strings.TrimSpace(name)
	}
	return cfg, nil
}

func (c *Controllers) commitAndOpenPRWithRepo(repoDir, commit, baseBranch, repoOwner, repoName string) (string, error) {
	cfg, err := loadGitHubAppConfigWithRepo(repoOwner, repoName)
	if err != nil {
		return "", err
	}
	token, err := githubInstallationToken(cfg)
	if err != nil {
		return "", err
	}
	if baseBranch == "" {
		baseBranch, err = githubDefaultBranch(cfg, token)
		if err != nil {
			return "", err
		}
	}
	shortSHA, err := gitShortSHA(repoDir, commit)
	if err != nil {
		return "", err
	}
	branch := fmt.Sprintf("dustbot-optimized-%s", shortSHA)

	if err := gitCheckoutNewBranch(repoDir, branch, baseBranch); err != nil {
		return "", err
	}
	changed, err := gitHasChanges(repoDir)
	if err != nil {
		return "", err
	}
	if !changed {
		return "", fmt.Errorf("no changes to commit after optimization")
	}
	if err := gitCommitAll(repoDir, cfg.BotName, cfg.BotEmail, commit); err != nil {
		return "", err
	}
	if err := gitPushBranch(repoDir, cfg, token, branch); err != nil {
		return "", err
	}
	return githubCreatePR(cfg, token, branch, baseBranch, commit)
}

func gitShortSHA(repoDir, commit string) (string, error) {
	cmd := exec.Command("git", "-C", repoDir, "rev-parse", "--short", commit)
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

func gitCheckoutNewBranch(repoDir, branch, baseBranch string) error {
	fetch := exec.Command("git", "-C", repoDir, "fetch", "origin", baseBranch)
	if err := fetch.Run(); err != nil {
		return err
	}
	checkout := exec.Command("git", "-C", repoDir, "checkout", "-B", branch, "origin/"+baseBranch)
	checkout.Stdout = os.Stdout
	checkout.Stderr = os.Stderr
	return checkout.Run()
}

func gitHasChanges(repoDir string) (bool, error) {
	cmd := exec.Command("git", "-C", repoDir, "status", "--porcelain")
	out, err := cmd.Output()
	if err != nil {
		return false, err
	}
	return strings.TrimSpace(string(out)) != "", nil
}

func gitCommitAll(repoDir, name, email, baseCommit string) error {
	configName := exec.Command("git", "-C", repoDir, "config", "user.name", name)
	_ = configName.Run()
	configEmail := exec.Command("git", "-C", repoDir, "config", "user.email", email)
	_ = configEmail.Run()

	add := exec.Command("git", "-C", repoDir, "add", "-A")
	if err := add.Run(); err != nil {
		return err
	}
	message := fmt.Sprintf("perf: automated optimizations for %s\n\nGenerated by dustbot on %s.", baseCommit, time.Now().Format(time.RFC3339))
	commit := exec.Command("git", "-C", repoDir, "commit", "-m", message)
	commit.Stdout = os.Stdout
	commit.Stderr = os.Stderr
	return commit.Run()
}

func gitPushBranch(repoDir string, cfg githubAppConfig, token, branch string) error {
	remote := fmt.Sprintf("https://x-access-token:%s@github.com/%s/%s.git", token, cfg.RepoOwner, cfg.RepoName)
	cmd := exec.Command("git", "-C", repoDir, "push", "-u", "--force-with-lease", remote, branch)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func githubInstallationToken(cfg githubAppConfig) (string, error) {
	privateKey, err := loadPrivateKey(cfg.PrivateKeyPath)
	if err != nil {
		return "", err
	}
	claims := jwt.RegisteredClaims{
		Issuer:    cfg.AppID,
		IssuedAt:  jwt.NewNumericDate(time.Now().Add(-1 * time.Minute)),
		ExpiresAt: jwt.NewNumericDate(time.Now().Add(9 * time.Minute)),
	}
	jwtToken := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	signed, err := jwtToken.SignedString(privateKey)
	if err != nil {
		return "", err
	}

	url := fmt.Sprintf("https://api.github.com/app/installations/%s/access_tokens", cfg.InstallationID)
	req, err := http.NewRequest(http.MethodPost, url, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+signed)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("User-Agent", "dustbot")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("github token error: %s", strings.TrimSpace(string(body)))
	}
	var payload struct {
		Token string `json:"token"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		return "", err
	}
	if payload.Token == "" {
		return "", fmt.Errorf("github token missing")
	}
	return payload.Token, nil
}

func githubDefaultBranch(cfg githubAppConfig, token string) (string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s", cfg.RepoOwner, cfg.RepoName)
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("User-Agent", "dustbot")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("github repo error: %s", strings.TrimSpace(string(body)))
	}
	var payload struct {
		DefaultBranch string `json:"default_branch"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		return "", err
	}
	if payload.DefaultBranch == "" {
		return "", fmt.Errorf("default branch missing")
	}
	return payload.DefaultBranch, nil
}

func githubCreatePR(cfg githubAppConfig, token, head, base, baseCommit string) (string, error) {
	title := fmt.Sprintf("perf: optimize %s", baseCommit)
	body := fmt.Sprintf("Automated perf-guided optimizations for commit %s.", baseCommit)
	payload := map[string]string{
		"title": title,
		"head":  head,
		"base":  base,
		"body":  body,
	}
	data, _ := json.Marshal(payload)
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/pulls", cfg.RepoOwner, cfg.RepoName)
	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(data))
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("User-Agent", "dustbot")
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		bodyResp, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("github pr error: %s", strings.TrimSpace(string(bodyResp)))
	}
	var pr struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&pr); err != nil {
		return "", err
	}
	if pr.HTMLURL == "" {
		return "", fmt.Errorf("pr url missing")
	}
	return pr.HTMLURL, nil
}

func loadPrivateKey(path string) (*rsa.PrivateKey, error) {
	keyData, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		return nil, err
	}
	privateKey, err := jwt.ParseRSAPrivateKeyFromPEM(keyData)
	if err != nil {
		return nil, err
	}
	return privateKey, nil
}
